[workspace]
release = false
git_only = false
publish = false
release_always = true
semver_check = false
pr_labels = ["release"]
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"
git_release_enable = false

[[package]]
name = "tuitbot-core"
release = true
publish = true
git_only = false
git_release_enable = false
changelog_update = false
git_tag_name = "tuitbot-core-v{{ version }}"
git_release_name = "tuitbot-core-v{{ version }}"

[[package]]
name = "tuitbot-mcp"
release = true
publish = true
git_only = false
git_release_enable = false
changelog_update = false
git_tag_name = "tuitbot-mcp-v{{ version }}"
git_release_name = "tuitbot-mcp-v{{ version }}"

[[package]]
name = "tuitbot-cli"
release = true
publish = true
git_only = false
git_release_enable = true
git_tag_name = "tuitbot-cli-v{{ version }}"
git_release_name = "tuitbot-cli-v{{ version }}"
changelog_path = "CHANGELOG.md"
changelog_include = ["tuitbot-core", "tuitbot-mcp"]
